name: tela_animada
description: Um novo projeto Flutter.

# Define a versão do aplicativo e o número de build.
# A versão segue o formato: major.minor.patch+build_number.
version: 1.0.0+1

# Define a versão do SDK do Dart necessária para o projeto.
environment:
  sdk: ">=2.12.0 <4.0.0"

# Dependências do projeto.
dependencies:
  flutter:
    sdk: flutter
  simple_animations: ^5.1.0
  page_transition: ^2.2.1
  cupertino_icons: ^1.0.8

# Dependências para testes durante o desenvolvimento.
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  # Garante que os ícones do Material Design estão incluídos no projeto.
  uses-material-design: true

  # Lista os assets usados no aplicativo.
  assets:
    - assets/images/
